services:
  noteapi:
    build: .
    ports:
      - "5800:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5700;Database=noteapi_dev;Username=postgres;Password=password123
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: noteapi_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5700:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d noteapi_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: